### ISSUE TITLE
Undefined variable 'curv' when decimation is set to 0

### ISSUE THREAD

**Issue by cmicek1** [dprice80/mni2fs#10]
Great package Darren! I just downloaded it and started playing around with it today, and noticed that when setting the FreeSurfer decimation flag to 0, there is a variable called 'curv' that is undefined in mni2fs_brain.m. It would appear that higher-resolution vertex locations are absent from the repository in the 'surf' folder; if these exist could you update/add accordingly? Seems like a pretty quick fix to me.

**Comment by cmicek1** [comment]
False alarm; apparently that's only a problem when modifying an existing struct

**Comment by dprice80** [comment]
Ah yes that would do it. Thanks for letting me know anyway.

**Comment by dprice80** [comment]
There is a new object oriented version cooking soon with many new features
