### ISSUE TITLE
Transformation matrices in 'surf'transmats.mat'?

### ISSUE THREAD

**Issue by cmicek1** [dprice80/mni2fs#11]
Hi Darren, could you elaborate on what each of the transformation matrices are in 'surf/transmats.mat'? The data I'm working with is a list of values for vertices of a different mesh that have coordinates in MNI-space (I believe with the origin in the top-right), and it would be great if I could convert these points into points on the FreeSurfer surface without having to first convert them into a NIFTI volume.

**Comment by cmicek1** [comment]
Also, I'm assuming this is the case but maybe you can clarify: The surface you have included is of the MNI brain, correct?

**Comment by dprice80** [comment]
The surface is the colin27 brain extracted using freesurfer. It's the same
canonical brain used in SPM and Fieldtrip, although I downloaded the full
resolution version, and reduced the number of vertices using
freesurfer decimation.

There should be a publication soon to explain all of this.

Thanks
Darren

**Comment by dprice80** [comment]
Sorry I've just realised this draft may not have been sent....

To do this you would need to coregister the surfaces in freesurfer. There
is no straightforward way to map from one surface to another if they do not
have the same vertex coordinates. If the vertices are very close you could
do nearest neighbour interpolation quite easily but depends on your needs.
The surface used in mni2fs is the colin27 brain.

Darren

**Comment by cmicek1** [comment]
Sweet, thanks! I did start out doing interpolation to start with, but it was pretty slow so what I wound up doing was substituting the Freesurfer surface in place of our initial surface in our pipeline, and that has been working pretty smoothly so far.
