### ISSUE TITLE
Cerebellum

### ISSUE THREAD

**Issue by PhilKuhnke** [dprice80/mni2fs#12]
Dear Darren,

first of all, thanks a lot for providing this wonderful toolbox! It makes (very pretty!) surface rendering of volumetric MRI data easier than I could've imagined.

As the title suggests I'm wondering if there is a way to also include the cerebellum in the rendering (and plot activations on it)? 

Thanks a lot in advance and all the best,
Phil

**Comment by dprice80** [comment]
Thank you very much Phil. Good to hear that people are finding it useful.

Unfortunately, cerebellum is not currently supported. Sorry about that.

Darren

**Comment by dprice80** [comment]
P.S. There is a major update coming soon that adds new features like animations (with a GUI slider) and composite images (so it can create left/right middle/lateral on the same plot). Should be available in the next few weeks.

**Comment by PhilKuhnke** [comment]
That sounds great! I'm especially looking forward to the latter option. Maybe a future update could also include the cerebellum?! ;)
