### ISSUE TITLE
Read GIFTI Error

### ISSUE THREAD

**Issue by PhilKuhnke** [dprice80/mni2fs#16]
Dear Darren,

unfortunately the most recent version of mni2fs does not work for me. When trying to run it (e.g. run_example.m), I get the following error: 

```
Error using read_gifti_file_standalone (line 20)
[GIFTI] Loading of XML file
/imaging/dp01/toolboxes/mni2fs_devel/convert/surf/rh.surf.gii failed.

Error in gifti (line 71)
                this = read_gifti_file_standalone(varargin{1},giftistruct);

Error in mni2fs_brain (line 128)
V = gifti('/imaging/dp01/toolboxes/mni2fs_devel/convert/surf/rh.surf.gii');

Error in mni2fs_auto (line 40)
S = mni2fs_brain(S);

Error in run_example (line 13)
mni2fs_auto(fullfile(toolboxpath, 'examples/AudMean.nii'),'rh') 
```

Versions of mni2fs from February 2019 or earlier work for me, but the June 2019 version doesn't. Do you have ideas how to fix this issue?

Thanks a lot in advance and all the best,
Phil

**Comment by rcalmus** [comment]
I have the same issue, although I fixed it by updating the path on line 128 to `V = gifti('./surf/rh.surf.gii');`

However, more problematic are the references to files not contained within the distribution, such as Line 15 of mni2fs_meshtovol.m:

`NII = load_nii('/imaging/dp01/templates/MNI152_T1_2mm.nii');`

I Googled this file and downloaded it to a local subfolder I named "templates", but it seems important that this be included in the repository.

Thank you in advance for your help.
