### ISSUE TITLE
Issue with included gifti version?

### ISSUE THREAD

**Issue by cMadan** [dprice80/mni2fs#2]
I tried running the code as-is, but was getting an error when loading the gii files, the error appears to be thrown by xml_parser from the included GifTI v1.4.

Removing the included version of GifTI toolbox and instead using v1.6 (http://www.artefact.tk/software/matlab/gifti/) appears to have solved the problem.

In case it's relevant, I'm running the code in MATLAB R2015b on a Mac.

**Comment by dprice80** [comment]
Hi. Thanks for letting me know, and sorry about the delayed response. I will update the included version of GifTI
